// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2a9JGibvxCGejRt5Q99OScnElXY1qC9c',
    appId: '1:73731485272:web:6a0a56d9cf868f3cf2a42d',
    messagingSenderId: '73731485272',
    projectId: 'blog-app-90122',
    authDomain: 'blog-app-90122.firebaseapp.com',
    storageBucket: 'blog-app-90122.appspot.com',
    measurementId: 'G-NHMLG29TRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9f5H9E2IeRALgus41j7yif8AIGiS-Sw',
    appId: '1:73731485272:android:24a197f56bd568f2f2a42d',
    messagingSenderId: '73731485272',
    projectId: 'blog-app-90122',
    storageBucket: 'blog-app-90122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCafH77y5-Hm3K3_hVe-QkyyMZM94ABIM8',
    appId: '1:73731485272:ios:fb5e2b49005186e6f2a42d',
    messagingSenderId: '73731485272',
    projectId: 'blog-app-90122',
    storageBucket: 'blog-app-90122.appspot.com',
    iosBundleId: 'com.example.blogAppCleanArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCafH77y5-Hm3K3_hVe-QkyyMZM94ABIM8',
    appId: '1:73731485272:ios:fb5e2b49005186e6f2a42d',
    messagingSenderId: '73731485272',
    projectId: 'blog-app-90122',
    storageBucket: 'blog-app-90122.appspot.com',
    iosBundleId: 'com.example.blogAppCleanArch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2a9JGibvxCGejRt5Q99OScnElXY1qC9c',
    appId: '1:73731485272:web:a9f2e741caf2071cf2a42d',
    messagingSenderId: '73731485272',
    projectId: 'blog-app-90122',
    authDomain: 'blog-app-90122.firebaseapp.com',
    storageBucket: 'blog-app-90122.appspot.com',
    measurementId: 'G-L5FZRZG71C',
  );
}
