name: Android Fastlane Firebase

on:
  push:
    branches:
      - deploy


  jobs:
    distribute_to_firebase:
      runs-on: ubuntu-latest
      steps:
        - name: checkout my repo code
          uses: actions/checkout@v2

        - name: setup JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'temurin'

        - name: install flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable

        - name: install ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: "3.2.3"
            bundler-cache: true
            working-directory: android

        - name: Build and Distribute
          env:
            FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          run: |
            bundle exec fastlane android firebase_distribution
            working-directory: android

