name: Android CI

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Deploy to Firebase App Distribution
        if: github.event_name == 'push' && github.ref == 'refs/heads/deploy'
        run: fastlane android firebase_distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

#name: Android Fastlane Firebase
#
#on:
#  push:
#    branches:
#      - deploy
#
#
#  jobs:
#    distribute_to_firebase:
#      runs-on: ubuntu-latest
#      steps:
#        - name: checkout my repo code
#          uses: actions/checkout@v2
#
#        - name: setup JDK 11
#          uses: actions/setup-java@v2
#          with:
#            java-version: '11'
#            distribution: 'temurin'
#
#        - name: install flutter
#          uses: subosito/flutter-action@v2
#          with:
#            channel: stable
#
#        - name: install ruby
#          uses: ruby/setup-ruby@v1
#          with:
#            ruby-version: "3.2.3"
#            bundler-cache: true
#            working-directory: android
#
#        - name: Build and Distribute
#          env:
#            FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
#          run: |
#            bundle exec fastlane android firebase_distribution
#            working-directory: android
#
